version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm install --legacy-peer-deps && npm run dev"